name: aws_test
on: push
jobs:
  build:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - name: install aws cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - name: push to sqs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_DEFAULT_OUTPUT: json
        run: aws sqs send-message --queue-url https://sqs.us-east-2.amazonaws.com/918511214686/test_queue --message-body github.ref
                
      - name: echo key
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: echo ${{ AWS_ACCESS_KEY_ID }}
