name: aws_test
on: push
jobs:
  build:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - name: install aws cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - name: push to sqs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws sqs send-message --queue-url https://sqs.us-east-2.amazonaws.com/918511214686/test_queue --message-body github.ref
